# Generated by Django 2.1.10 on 2019-10-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rate_beer", "0002_auto_20191014_2055")]

    operations = [
        migrations.AddField(
            model_name="rating", name="public", field=models.BooleanField(default=False)
        )
    ]
